name: background_beacon_sdk
description: Flutter SDK for detecting BLE beacons in background on iOS, Android (GMS) and Huawei (HMS) devices.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.0.1
  http: ^1.6.0
  plugin_platform_interface: ^2.1.8
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        # TODO: rename package to your real organization
        package: com.example.background_beacon_sdk
        pluginClass: BackgroundBeaconSdkPlugin
      ios:
        pluginClass: BackgroundBeaconSdkPlugin
